FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Les variables d'environnement seront fournies lors du run
ENV DB_HOST="localhost"
ENV DB_USER="root"
ENV DB_PASSWORD="rat"
ENV DB_NAME="microapp"

CMD ["npm", "test"]