name: Tests et Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    name: Tests unitaires
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Configuration de Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Installation des dépendances
      run: npm ci
    - name: Installation de jest
      run: npm install --save-dev jest
    - name: Exécution des tests
      run: npm test
    - name: Mise à jour du README
      if: success()
      run: |
        echo "# microApp" > $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## État des tests" >> $GITHUB_STEP_SUMMARY
        echo "✅ Tous les tests ont réussi - $(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
        